# Generated by Django 4.0.10 on 2026-09-13 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0004_firstsolutionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_key', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('rpc_name', models.CharField(blank=True, default='', max_length=100)),
                ('pub_type', models.CharField(blank=True, default='', max_length=30)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('category', models.CharField(choices=[('PUBLICATION', 'Publicación Top'), ('FIRST_SOLUTION', 'First Solution'), ('SCHEDULER', 'Programador'), ('SCRAPER', 'Scraper BOCA'), ('SYSTEM', 'Sistema')], default='SYSTEM', max_length=30)),
                ('message', models.TextField()),
                ('post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'execution_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
